pipeline {
  agent any
  tools { 
        maven 'Maven-3.5.4'
        jdk 'JDK-8'
  }
  stages {
    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace... */
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'cd hellow-world && mvn -B -DskipTests clean package'
      }
    }
    stage('Docker Build') {
      steps {
        sh 'cd hellow-world && /usr/bin/docker build -t satheeshch/helloworld:latest .'
      }
    }
    stage('Push image') {
      steps {
        withDockerRegistry([credentialsId: '5b5cee8b-741d-4ee6-b323-a39164efde8e', url: "https://index.docker.io/v1/"]) {
          sh '/usr/bin/docker push satheeshch/helloworld:latest'
        }
      }
    }
  }
}
