pipeline {
  agent any
  tools { 
        maven 'Maven-3.5.4' 
  }
  stages {
    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'cd hellow-world && mvn -B -DskipTests clean package'
      }
    }
    stage('Docker Build') {
      steps {
        sh '/usr/bin/docker build -t $docker_user/helloworld:latest .'
      }
    }
    stage('Push image') {
      steps {
        withDockerRegistry([credentialsId: 'docker_creds', url: "https://index.docker.io/v1/"]) {
          sh '/usr/bin/docker tag helloworld $docker_user/helloworld'
          sh '/usr/bin/docker push $docker_user/helloworld:latest'
        }
      }
    }
  }
}
