pipeline {
  agent any
  tools { 
        maven 'MAVEN'
      /* jdk 'JAVA_HOME' */
  }
  stages {
    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace... */
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'cd hellow-world && mvn -B -DskipTests clean package'
        sh 'echo $USER'
        sh 'echo whoami'
      }
    }
    stage('Docker Build') {
      steps {
        sh 'cd hellow-world && docker build -t thamarana/helloworld2:latest.'
      }
    }
    stage('Push image') {
      steps {
         withDockerRegistry([credentialsId: 'dockerhub', url: "https://index.docker.io/v1/"]) { 
          sh 'docker push thamarana/helloworld2:latest'
     } 
      }
    }
  }
}
